version: '3.0'
services:
  api:
    image: docker-registry.data.amsterdam.nl/datapunt/external-data-scrapers:${ENVIRONMENT}
    environment:
      ADP_USE_SSL_CERT:
      DATABASE_NAME: externaldata
      DATABASE_USER: externaldata
      DATABASE_PASSWORD:
      DATABASE_HOST:
      WATERNET_USERNAME:
      WATERNET_PASSWORD:
