version: '3.0'
services:
  importer:
    image: repo.data.amsterdam.nl/datapunt/external-data-scrapers_importer:${ENVIRONMENT}
    # build: ../..
    environment:
      ENVIRONMENT:
      OVERRIDE_DATABASE:
      DATABASE_OVERRIDE_HOST: 
      DATABASE_OVERRIDE_NAME: externaldata
      DATABASE_OVERRIDE_USER: externaldata
      DATABASE_OVERRIDE_PORT: 5432
      DATABASE_OVERRIDE_PASSWORD: 
      IMPORT_LIMIT:
      DROP:
      WFS:
      PYTHONPATH: "/app"
