version: '2.0'
services:
  api: 
    image: repo.data.amsterdam.nl/datapunt/external-data-scrapers:${ENVIRONMENT}
    ports:
      - "8001:8001"
    links:
      - database
    environment:
      - DATABASE_NAME=externaldata
      - DATABASE_USER=externaldata
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
